import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:printing/printing.dart';

/// PDF Viewer Page - Displays a PDF document with preview, sharing, and printing capabilities.
/// 
/// This widget provides a corporate-styled interface for viewing PDF documents
/// generated by the application, with proper error handling and loading states.
class PdfViewerPage extends StatelessWidget {
  /// The title displayed in the AppBar
  final String title;
  
  /// The filename to use when sharing or saving the PDF (e.g., "Servis_Raporu_2025.pdf")
  final String pdfFileName;
  
  /// Async function that generates the PDF bytes
  final Future<Uint8List> Function() pdfGenerator;

  const PdfViewerPage({
    super.key,
    required this.title,
    required this.pdfFileName,
    required this.pdfGenerator,
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF1F5F9), // Light grey background
      appBar: AppBar(
        title: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              title,
              style: const TextStyle(
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            Text(
              pdfFileName,
              style: const TextStyle(
                fontSize: 12,
                color: Colors.white70,
                fontWeight: FontWeight.normal,
              ),
            ),
          ],
        ),
        centerTitle: false,
        backgroundColor: const Color(0xFF0F172A), // Dark primary color
        elevation: 0,
        iconTheme: const IconThemeData(color: Colors.white),
      ),
      body: Theme(
        // Force toolbar icons to match app's primary color
        data: Theme.of(context).copyWith(
          colorScheme: Theme.of(context).colorScheme.copyWith(
                primary: const Color(0xFF0F172A),
              ),
        ),
        child: PdfPreview(
          build: (format) => pdfGenerator(),
          // File naming for sharing/saving
          pdfFileName: pdfFileName,
          // Action customization
          canChangeOrientation: false,
          canChangePageFormat: false,
          canDebug: false,
          allowSharing: true,
          allowPrinting: true,
          // Custom loading state
          loadingWidget: const Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                CircularProgressIndicator(
                  color: Color(0xFF0F172A),
                ),
                SizedBox(height: 16),
                Text(
                  'Belge Hazırlanıyor...',
                  style: TextStyle(
                    fontSize: 16,
                    color: Color(0xFF64748B),
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ],
            ),
          ),
          // Custom error state
          onError: (context, error) => Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Icon(
                  Icons.error_outline,
                  size: 64,
                  color: Colors.red.shade400,
                ),
                const SizedBox(height: 16),
                const Text(
                  'Belge Görüntülenemedi',
                  style: TextStyle(
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                    color: Color(0xFF0F172A),
                  ),
                ),
                const SizedBox(height: 8),
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 32),
                  child: Text(
                    error.toString(),
                    textAlign: TextAlign.center,
                    style: const TextStyle(
                      fontSize: 14,
                      color: Color(0xFF64748B),
                    ),
                  ),
                ),
                const SizedBox(height: 24),
                ElevatedButton.icon(
                  onPressed: () {
                    // Retry by rebuilding the widget
                    Navigator.of(context).pop();
                  },
                  icon: const Icon(Icons.arrow_back),
                  label: const Text('Geri Dön'),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF0F172A),
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(
                      horizontal: 24,
                      vertical: 12,
                    ),
                  ),
                ),
              ],
            ),
          ),
          // Background color for scroll view
          scrollViewDecoration: const BoxDecoration(
            color: Color(0xFFF1F5F9),
          ),
        ),
      ),
    );
  }
}
