-- İŞ EMİRLERİ İÇİN KULLANILAN PARÇALAR TABLOSU
-- Bu tablo, bir iş emrinde stoktan düşülen parçaları tutar.

CREATE TABLE public.ticket_parts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id uuid NOT NULL REFERENCES public.tickets(id) ON DELETE CASCADE,
    inventory_id bigint NOT NULL REFERENCES public.inventory(id) ON DELETE CASCADE,
    quantity integer NOT NULL DEFAULT 1,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Politikaları
ALTER TABLE public.ticket_parts ENABLE ROW LEVEL SECURITY;

-- Herkes görebilir
CREATE POLICY "Herkes parçaları görebilir" ON public.ticket_parts FOR SELECT USING (true);

-- Sadece yetkililer ve teknisyenler ekleyebilir/düzenleyebilir/silebilir
CREATE POLICY "Yetkililer parça ekleyebilir" ON public.ticket_parts FOR INSERT 
WITH CHECK (
    auth.uid() IN (
        SELECT id FROM public.profiles 
        WHERE role IN ('admin', 'manager', 'technician', 'supervisor')
    )
);

CREATE POLICY "Yetkililer parça silebilir" ON public.ticket_parts FOR DELETE 
USING (
    auth.uid() IN (
        SELECT id FROM public.profiles 
        WHERE role IN ('admin', 'manager', 'technician', 'supervisor')
    )
);

CREATE POLICY "Yetkililer parça güncelleyebilir" ON public.ticket_parts FOR UPDATE
USING (
    auth.uid() IN (
        SELECT id FROM public.profiles 
        WHERE role IN ('admin', 'manager', 'technician', 'supervisor')
    )
);
