begin;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  message text not null,
  data jsonb not null default '{}'::jsonb,
  is_read boolean not null default false,
  created_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.notifications
  add column if not exists user_id uuid references auth.users,
  add column if not exists title text,
  add column if not exists message text,
  add column if not exists data jsonb not null default '{}'::jsonb,
  add column if not exists is_read boolean not null default false,
  add column if not exists created_at timestamptz not null default timezone('utc'::text, now());

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'notifications'
      and column_name = 'team_id'
  ) then
    execute 'alter table public.notifications alter column team_id drop not null';
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'notifications'
      and column_name = 'card_id'
  ) then
    execute 'alter table public.notifications alter column card_id drop not null';
  end if;

  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'notifications'
      and column_name = 'type'
  ) then
    execute 'alter table public.notifications alter column "type" drop not null';
  end if;
end $$;

update public.notifications
set data = '{}'::jsonb
where data is null;

create index if not exists idx_notifications_user_created_at
  on public.notifications(user_id, is_read, created_at desc);

alter table public.notifications enable row level security;

drop policy if exists notifications_select_policy on public.notifications;
drop policy if exists notifications_update_policy on public.notifications;
drop policy if exists notifications_insert_policy on public.notifications;
drop policy if exists notifications_delete_policy on public.notifications;
drop policy if exists "Users can view their own notifications" on public.notifications;
drop policy if exists "Users can update their own notifications (mark as read)" on public.notifications;
drop policy if exists "Authenticated users can insert notifications" on public.notifications;

create policy notifications_select_policy on public.notifications
  for select
  using (auth.uid() = user_id);

create policy notifications_update_policy on public.notifications
  for update
  using (auth.uid() = user_id);

create policy notifications_insert_policy on public.notifications
  for insert
  with check (auth.role() = 'authenticated');

create policy notifications_delete_policy on public.notifications
  for delete
  using (auth.uid() = user_id);

create table if not exists public.user_push_tokens (
  user_id uuid primary key references auth.users(id) on delete cascade,
  onesignal_player_id text,
  device_type text,
  updated_at timestamptz not null default timezone('utc'::text, now())
);

alter table public.user_push_tokens
  add column if not exists onesignal_player_id text,
  add column if not exists device_type text,
  add column if not exists updated_at timestamptz not null default timezone('utc'::text, now());

alter table public.user_push_tokens enable row level security;

drop policy if exists user_push_tokens_policy on public.user_push_tokens;

create policy user_push_tokens_policy on public.user_push_tokens
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

commit;
