-- Inverter hizli referans degerleri
-- Supabase SQL Editor'da bir kez calistirin.

create table if not exists public.inverter_reference_values (
    id bigint generated by default as identity primary key,
    device_brand text default '' not null,
    device_model text default '' not null,
    title text not null,
    register_address text default '' not null,
    stored_value text default '' not null,
    unit text default '' not null,
    category text default 'general' not null,
    note text default '' not null,
    sort_order integer default 0 not null,
    created_by uuid references auth.users(id),
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

create index if not exists idx_inverter_reference_values_device
    on public.inverter_reference_values(device_brand, device_model);

create index if not exists idx_inverter_reference_values_order
    on public.inverter_reference_values(device_brand, device_model, category, sort_order, title);

alter table public.inverter_reference_values enable row level security;

drop policy if exists inverter_reference_values_select_policy on public.inverter_reference_values;
create policy inverter_reference_values_select_policy
    on public.inverter_reference_values
    for select
    using (auth.role() = 'authenticated');

drop policy if exists inverter_reference_values_insert_policy on public.inverter_reference_values;
create policy inverter_reference_values_insert_policy
    on public.inverter_reference_values
    for insert
    with check (
        auth.role() = 'authenticated'
        and created_by = auth.uid()
    );

drop policy if exists inverter_reference_values_update_policy on public.inverter_reference_values;
create policy inverter_reference_values_update_policy
    on public.inverter_reference_values
    for update
    using (auth.role() = 'authenticated')
    with check (auth.role() = 'authenticated');

drop policy if exists inverter_reference_values_delete_policy on public.inverter_reference_values;
create policy inverter_reference_values_delete_policy
    on public.inverter_reference_values
    for delete
    using (auth.role() = 'authenticated');

create or replace function public.update_inverter_reference_values_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

drop trigger if exists inverter_reference_values_updated_at_trigger
    on public.inverter_reference_values;

create trigger inverter_reference_values_updated_at_trigger
    before update on public.inverter_reference_values
    for each row
    execute function public.update_inverter_reference_values_updated_at();
