alter table public.inventory
add column if not exists barcode text;

create unique index if not exists inventory_barcode_unique_idx
on public.inventory (barcode)
where barcode is not null and barcode <> '';

create table if not exists public.stock_movements (
    id bigint generated by default as identity primary key,
    inventory_id bigint not null references public.inventory(id) on delete cascade,
    movement_type text not null check (movement_type in ('in', 'out')),
    quantity integer not null check (quantity > 0),
    quantity_before integer not null default 0,
    quantity_after integer not null default 0,
    reason text,
    destination text,
    note text,
    created_by uuid references public.profiles(id) on delete set null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists stock_movements_inventory_id_idx
on public.stock_movements (inventory_id);

create index if not exists stock_movements_created_at_idx
on public.stock_movements (created_at desc);

alter table public.stock_movements enable row level security;

drop policy if exists "stock_movements_select_all" on public.stock_movements;
create policy "stock_movements_select_all"
on public.stock_movements for select
using (true);

drop policy if exists "stock_movements_insert_staff" on public.stock_movements;
create policy "stock_movements_insert_staff"
on public.stock_movements for insert
with check (
    auth.uid() in (
        select id from public.profiles
        where role in ('admin', 'manager', 'supervisor')
    )
);

create or replace function public.register_stock_movement(
    p_inventory_id bigint,
    p_movement_type text,
    p_quantity integer,
    p_reason text default null,
    p_destination text default null,
    p_note text default null
)
returns void
language plpgsql
as $$
declare
    v_before integer;
    v_after integer;
begin
    if p_movement_type not in ('in', 'out') then
        raise exception 'Gecersiz stok hareketi.';
    end if;

    if p_quantity <= 0 then
        raise exception 'Adet 0dan buyuk olmali.';
    end if;

    select quantity
    into v_before
    from public.inventory
    where id = p_inventory_id
    for update;

    if not found then
        raise exception 'Stok kaydi bulunamadi.';
    end if;

    if p_movement_type = 'in' then
        v_after := v_before + p_quantity;
    else
        v_after := v_before - p_quantity;
    end if;

    if v_after < 0 then
        raise exception 'Stok yetersiz! Mevcut: %', v_before;
    end if;

    update public.inventory
    set quantity = v_after
    where id = p_inventory_id;

    insert into public.stock_movements (
        inventory_id,
        movement_type,
        quantity,
        quantity_before,
        quantity_after,
        reason,
        destination,
        note,
        created_by
    )
    values (
        p_inventory_id,
        p_movement_type,
        p_quantity,
        v_before,
        v_after,
        nullif(trim(coalesce(p_reason, '')), ''),
        nullif(trim(coalesce(p_destination, '')), ''),
        nullif(trim(coalesce(p_note, '')), ''),
        auth.uid()
    );
end;
$$;
