-- Create notifications table
create table public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  message text not null,
  data jsonb,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS policies
alter table public.notifications enable row level security;

create policy "Users can view their own notifications"
  on public.notifications for select
  using (auth.uid() = user_id);

create policy "Users can update their own notifications (mark as read)"
  on public.notifications for update
  using (auth.uid() = user_id);

-- Only service role or admin functions should insert notifications usually, 
-- but for simplicity if the app inserts it via client (not recommended for security but common in rapid dev),
-- we might need insert policy. 
-- However, since NotificationService runs on client, the logged in user is the sender.
-- But the sender needs to insert for *other* users. 
-- Standard RLS prevents inserting for others unless we use a function with security definer 
-- or give insert permission.
-- For now, let's allow authenticated users to insert (assuming they are authorized logic-wise in app).
-- A better approach is a Postgres function 'send_notification' that inserts and calls OneSignal, 
-- but we are doing logic in Dart.
create policy "Authenticated users can insert notifications"
  on public.notifications for insert
  with check (auth.role() = 'authenticated');

