-- 1. PARTNER FİRMALAR TABLOSU
CREATE TABLE IF NOT EXISTS public.partners (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    contact_info text,
    logo_url text
);

-- 2. KULLANICI PROFİLLERİNE PARTNER BAĞLANTISI EKLEME
-- Tablo adı: profiles
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS partner_id bigint REFERENCES public.partners(id);

-- 3. İŞ EMİRLERİNE (TICKETS) PARTNER BAĞLANTISI EKLEME
ALTER TABLE public.tickets 
ADD COLUMN IF NOT EXISTS partner_id bigint REFERENCES public.partners(id);

-- 4. GÜVENLİK POLİTİKALARI (RLS - Row Level Security)
-- Bu kısım "STRICT RULE" dediğin kuralı uygular.

-- Önce RLS'i aktif et
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;

-- Politika: Partner Kullanıcıları SADECE kendi partner_id'sine sahip işleri görebilir.
-- Adminler her şeyi görebilir.
-- Önceki politikalarda çakışma olmaması için policy ismini özelleştirdik
CREATE POLICY "Partnerler sadece kendi işlerini görür_v2" ON public.tickets
FOR SELECT
USING (
  (auth.uid() IN (
    -- Kullanıcı admin mi?
    SELECT id FROM public.profiles WHERE role = 'admin'
  ))
  OR
  (partner_id IN (
    -- Kullanıcının bağlı olduğu partner_id ile işin partner_id'si eşleşiyor mu?
    SELECT partner_id FROM public.profiles WHERE id = auth.uid()
  ))
);
