String productCategoryTurkishLabel(String raw) {
  final category = raw.trim();
  final key = category.toLowerCase().replaceAll(RegExp(r'\s+'), ' ');
  const labels = <String, String>{
    '': 'Kategorisiz',
    'genel': 'Genel',
    'accessories': 'Aksesuarlar',
    'actuators': 'Aktüatörler',
    'air treatment': 'Hava Şartlandırma',
    'airflow control valves': 'Hava Akış Kontrol Vanaları',
    'btu and flow meters': 'BTU ve Debi Sayaçları',
    'connected homes': 'Bağlantılı Ev Sistemleri',
    'control valves & actuators': 'Kontrol Vanaları ve Aktüatörler',
    'controller accessories': 'Kontrolör Aksesuarları',
    'controller service parts': 'Kontrolör Servis Parçaları',
    'core brand app': 'Temel Marka Uygulamaları',
    'dedicated io': 'Özel I/O Modülleri',
    'digital airflow control valves': 'Dijital Hava Akış Kontrol Vanaları',
    'discrete communication modules': 'Ayrık Haberleşme Modülleri',
    'ebi core platform': 'EBI Ana Platformu',
    'hmi': 'HMI / Operatör Panelleri',
    'hmis': 'HMI / Operatör Panelleri',
    'industrial switches': 'Endüstriyel Ağ Anahtarları',
    'inverter': 'İnvertörler',
    'legacy products': 'Eski Nesil Ürünler',
    'lighting control': 'Aydınlatma Kontrolü',
    'local hmi': 'Yerel HMI',
    'plant controllers w/ onboard io': 'Dahili I/O’lu Tesis Kontrolörleri',
    'plant controllers w/o onboard io': 'Dahili I/O’suz Tesis Kontrolörleri',
    'pressure': 'Basınç',
    'raw materials and shared components': 'Hammaddeler ve Ortak Bileşenler',
    'remote temperature controllers': 'Uzak Sıcaklık Kontrolörleri',
    'sensor': 'Sensörler',
    'sensors and wall modules': 'Sensörler ve Duvar Modülleri',
    'software maintenance agreement': 'Yazılım Bakım Sözleşmesi',
    'submetering': 'Alt Ölçüm',
    'supervisor cloud': 'Bulut Üst Yönetim',
    'system wide hmi': 'Sistem Geneli HMI',
    'thermostats': 'Termostatlar',
    'unitary controllers': 'Paket Cihaz Kontrolörleri',
    'vav controllers': 'VAV Kontrolörleri',
    'valve & actuator assemblies': 'Vana ve Aktüatör Grupları',
    'valves': 'Vanalar',
    'zone controllers': 'Zon Kontrolörleri',
  };
  return labels[key] ?? (category.isEmpty ? 'Kategorisiz' : category);
}
