-- Uzal Teklif demo data
-- Run after supabase/schema.sql.

insert into public.market_rates (
  code,
  label,
  unit_label,
  value,
  is_fallback,
  sort_order,
  updated_at
) values
  ('USDTRY', 'Dolar', '1 USD', 38.12, true, 10, timezone('utc', now())),
  ('EURTRY', 'Euro', '1 EUR', 41.26, true, 20, timezone('utc', now()))
on conflict (code) do update set
  label = excluded.label,
  unit_label = excluded.unit_label,
  value = excluded.value,
  is_fallback = excluded.is_fallback,
  sort_order = excluded.sort_order,
  updated_at = excluded.updated_at;

insert into public.products (
  id,
  code,
  name,
  category,
  brand,
  model,
  unit,
  currency_code,
  sale_price,
  stock_quantity,
  minimum_stock,
  vat_rate,
  lead_time,
  description,
  technical_summary,
  is_active,
  specifications
) values
  (
    'product-001',
    'SNS-QAE-2120',
    'Kanal Tipi Sicaklik Sensoru',
    'Sensor',
    'Siemens',
    'QAE2120.010',
    'adet',
    'TL',
    1850,
    26,
    8,
    20,
    '2 is gunu',
    'HVAC uygulamalari icin kanal tipi sicaklik olcumu yapan dayanikli sensor.',
    'Olcum araligi -50/+80 C, PT1000, IP54',
    true,
    '{
      "olculen_parametre": "Sicaklik",
      "sensor_tipi": "PT1000 (Class B)",
      "olcum_araligi": "-50 / +80 C",
      "dogruluk": "+/- 0.5 C @ 25 C",
      "tepki_suresi": "12 sn",
      "cikis_sinyali": "Pasif (PT1000)",
      "besleme_gerilimi": "Gerekmez (pasif sensor)",
      "baglanti": "2 telli, terminal bloklu",
      "montaj_tipi": "Kanal / daldirmali flans",
      "koruma_sinifi": "IP54",
      "calisma_sicakligi": "-30 / +80 C",
      "prob_uzunlugu": "150 mm"
    }'::jsonb
  ),
  (
    'product-002',
    'DDC-PXC7-E400',
    'DDC Kontrolor',
    'DDC Kontrolor',
    'Siemens',
    'PXC7.E400',
    'adet',
    'USDTRY',
    420,
    7,
    4,
    20,
    '1 hafta',
    'Bina otomasyonu projeleri icin network destekli merkezi kontrolor.',
    'BACnet IP, moduler I/O, 24 VAC besleme',
    true,
    '{
      "besleme_gerilimi": "24 VAC / 24 VDC",
      "haberlesme_protokolu": "BACnet IP, Modbus TCP, RS-485",
      "programlama_dili": "IEC 61131-3",
      "web_arayuzu": "Dahili HTML5 panel",
      "dijital_giris": "8 kanal",
      "dijital_cikis": "4 kanal role cikisi",
      "analog_giris": "8 kanal universal",
      "analog_cikis": "4 kanal",
      "koruma_sinifi": "IP20",
      "montaj": "DIN ray 35 mm"
    }'::jsonb
  ),
  (
    'product-003',
    'INV-3P-11KW',
    'Frekans Inverteri',
    'Inverter',
    'Delta',
    'CP2000 11kW',
    'adet',
    'EURTRY',
    515,
    3,
    5,
    20,
    '10 gun',
    'Pompa ve fan uygulamalari icin 3 faz surucu cozum paketi.',
    '3 faz 380V, 11 kW, dahili PID, Modbus RTU',
    true,
    '{
      "besleme_gerilimi": "3x380-480 VAC",
      "kontrol_modu": "V/F, SVC",
      "frekans_araligi": "0 Hz - 599 Hz",
      "pid_fonksiyonu": "Var",
      "haberlesme": "Modbus RTU RS-485",
      "koruma_sinifi": "IP20",
      "guc": "11 kW",
      "nominal_akim": "24 A"
    }'::jsonb
  ),
  (
    'product-004',
    'MEC-VLV-2W-65',
    'Iki Yollu Kontrol Vanasi',
    'Mekanik',
    'Belimo',
    'H650S',
    'adet',
    'TL',
    6420,
    14,
    6,
    20,
    '3 is gunu',
    'Sicak ve soguk su hatlari icin kontrol vanasi ve aktuatore uygun govde.',
    'DN65, PN16, sfero dokum',
    true,
    '{
      "nominal_cap": "DN65",
      "basinc_sinifi": "PN16",
      "govde_malzemesi": "Sfero dokum",
      "baglanti_tipi": "Flansli",
      "kv_degeri": "63 m3/h",
      "sizdirmazlik": "Class IV"
    }'::jsonb
  ),
  (
    'product-005',
    'AUT-ACT-NM24A',
    'Damper Aktuatoru',
    'Otomasyon',
    'Belimo',
    'NM24A-SR',
    'adet',
    'USDTRY',
    138,
    18,
    6,
    20,
    '4 is gunu',
    'Hava damper uygulamalari icin modulating kontrol destekli aktuator.',
    '10 Nm, 24 VAC/DC, 0-10V kontrol, IP54',
    true,
    '{
      "tork": "10 Nm",
      "calisma_suresi": "150 sn",
      "yay_donus": "Yok",
      "besleme_gerilimi": "24 VAC / 24 VDC",
      "kontrol_sinyali": "0-10 V DC",
      "koruma_sinifi": "IP54"
    }'::jsonb
  )
on conflict (id) do update set
  code = excluded.code,
  name = excluded.name,
  category = excluded.category,
  brand = excluded.brand,
  model = excluded.model,
  unit = excluded.unit,
  currency_code = excluded.currency_code,
  sale_price = excluded.sale_price,
  stock_quantity = excluded.stock_quantity,
  minimum_stock = excluded.minimum_stock,
  vat_rate = excluded.vat_rate,
  lead_time = excluded.lead_time,
  description = excluded.description,
  technical_summary = excluded.technical_summary,
  is_active = excluded.is_active,
  specifications = excluded.specifications;

insert into public.quotes (
  id,
  code,
  customer_name,
  customer_company,
  title,
  note,
  display_unit,
  subtotal_tl,
  items,
  hidden_costs,
  market_snapshot,
  document_profile,
  public_token,
  payment_method,
  payment_term_days,
  hide_prices,
  sections,
  status,
  created_at,
  cari_id,
  created_by_name
) values (
  'seed-001',
  'UZ-260420-101530',
  'Ayse Kaya',
  'Marmara Endustri',
  'Lazer Kesim ve Montaj Paketi',
  'Teslim suresi 7 is gunu. KDV harictir.',
  'USDTRY',
  23960,
  '[
    {
      "id": "line-1",
      "description": "Sase imalat kalemi",
      "quantity": 3,
      "unit": "adet",
      "unit_price_tl": 18500,
      "discount_rate": 4,
      "section_id": ""
    },
    {
      "id": "line-2",
      "description": "Boya ve paketleme",
      "quantity": 1,
      "unit": "paket",
      "unit_price_tl": 6200,
      "discount_rate": 0,
      "section_id": ""
    }
  ]'::jsonb,
  '[]'::jsonb,
  '[
    {"code": "USDTRY", "label": "Dolar", "unit_label": "1 USD", "value": 38.12, "updated_at": "2026-04-20T10:15:30Z"},
    {"code": "EURTRY", "label": "Euro", "unit_label": "1 EUR", "value": 41.26, "updated_at": "2026-04-20T10:15:30Z"}
  ]'::jsonb,
  '{
    "company_name": "UZAL TEKNIK",
    "company_tagline": "Mekanik ve Otomasyon Cozumleri",
    "company_phone": "+90 216 000 00 00",
    "company_email": "teklif@uzalteknik.com",
    "company_website": "www.uzalteknik.com",
    "company_address": "Istanbul, Turkiye",
    "prepared_by_name": "Ali Han",
    "prepared_by_title": "Satis Muhendisi",
    "prepared_by_phone": "+90 555 100 10 10",
    "prepared_by_email": "alihan@uzalteknik.com",
    "customer_contact_title": "Satinalma Muduru",
    "customer_phone": "+90 532 400 20 20",
    "customer_email": "satinalma@marmaraendustri.com",
    "validity_text": "15 gun",
    "payment_terms": "Pesin veya mutabakata gore vade",
    "delivery_terms": "7 is gunu"
  }'::jsonb,
  'demo-token',
  'cash',
  0,
  false,
  '[]'::jsonb,
  'draft',
  '2026-04-20T10:15:30Z',
  '',
  'Ali Han'
)
on conflict (id) do update set
  code = excluded.code,
  customer_name = excluded.customer_name,
  customer_company = excluded.customer_company,
  title = excluded.title,
  note = excluded.note,
  display_unit = excluded.display_unit,
  subtotal_tl = excluded.subtotal_tl,
  items = excluded.items,
  hidden_costs = excluded.hidden_costs,
  market_snapshot = excluded.market_snapshot,
  document_profile = excluded.document_profile,
  public_token = excluded.public_token,
  payment_method = excluded.payment_method,
  payment_term_days = excluded.payment_term_days,
  hide_prices = excluded.hide_prices,
  sections = excluded.sections,
  status = excluded.status,
  created_at = excluded.created_at,
  cari_id = excluded.cari_id,
  created_by_name = excluded.created_by_name;
