import 'dart:convert';
import 'dart:io';

const _typeByColumn = <int, String>{
  1: 'aiActive',
  2: 'aiPassive',
  3: 'ao',
  4: 'di',
  5: 'doOutput',
};

void main(List<String> arguments) {
  if (arguments.length != 2) {
    stderr.writeln(
      'Kullanım: dart run tool/generate_discovery_library.dart '
      '<kaynak.txt> <hedef.g.dart>',
    );
    exitCode = 64;
    return;
  }

  final source = File(arguments[0]);
  if (!source.existsSync()) {
    stderr.writeln('Kaynak dosya bulunamadı: ${source.path}');
    exitCode = 66;
    return;
  }

  final templates = _parseTemplates(
    const LineSplitter().convert(source.readAsStringSync(encoding: utf8)),
  );
  File(arguments[1])
    ..createSync(recursive: true)
    ..writeAsStringSync(_render(templates), encoding: utf8);

  final pointCount = templates.fold<int>(
    0,
    (total, template) => total + template.points.length,
  );
  stdout.writeln(
    '${templates.length} cihaz şablonu ve $pointCount nokta üretildi.',
  );
}

List<_Template> _parseTemplates(List<String> lines) {
  final templates = <_Template>[];
  _Template? current;
  var afterBlank = true;

  for (final rawLine in lines) {
    if (rawLine.trim().isEmpty) {
      afterBlank = true;
      continue;
    }

    final cells = rawLine.split('\t');
    while (cells.length < 6) {
      cells.add('');
    }
    final name = cells.first.trim();
    if (name.isEmpty) {
      afterBlank = false;
      continue;
    }

    final quantities = <int, int>{};
    for (var column = 1; column <= 5; column++) {
      final quantity = int.tryParse(cells[column].trim());
      if (quantity != null && quantity > 0) quantities[column] = quantity;
    }

    if (afterBlank && quantities.isEmpty) {
      current = _Template(name);
      templates.add(current);
      afterBlank = false;
      continue;
    }
    afterBlank = false;

    if (current == null || _isSpare(name)) continue;
    if (quantities.isEmpty) {
      if (_isDamperStartStop(name)) {
        current.points.add(_Point(name, 'doOutput', 1));
      }
      continue;
    }

    for (final entry in quantities.entries) {
      current.points.add(_Point(name, _typeByColumn[entry.key]!, entry.value));
    }
  }

  final usable = templates
      .where((template) => template.points.isNotEmpty)
      .toList();

  // Sistemde zaten aynı altı noktaya sahip standart kazan şablonu var.
  usable.removeWhere((template) => template.name == 'ISITMA KAZANI');
  for (final template in usable) {
    if (template.name == 'POMPA') {
      template.name = 'POMPA (2\'Lİ STANDART)';
    }
  }
  return usable;
}

bool _isSpare(String value) {
  final upper = value.toUpperCase();
  return upper == 'YEDEK' || upper == 'SPARE';
}

bool _isDamperStartStop(String value) {
  final upper = value.toUpperCase();
  return upper.contains('DAMPER') && upper.contains('START/STOP');
}

String _render(List<_Template> templates) {
  final keys = <String>{};
  final buffer = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by tool/generate_discovery_library.dart.')
    ..writeln()
    ..writeln("part of 'discovery_templates.dart';")
    ..writeln()
    ..writeln('abstract final class DiscoveryImportedTemplates {')
    ..writeln('  static const values = <DiscoveryDeviceTemplate>[');

  for (final template in templates) {
    var key = 'library-${_slug(template.name)}';
    var suffix = 2;
    final baseKey = key;
    while (!keys.add(key)) {
      key = '$baseKey-$suffix';
      suffix++;
    }
    buffer
      ..writeln('    DiscoveryDeviceTemplate(')
      ..writeln("      key: '${_escape(key)}',")
      ..writeln("      name: '${_escape(template.name)}',")
      ..writeln(
        "      categoryName: '${_escape(_categoryFor(template.name))}',",
      )
      ..writeln('      points: [');
    for (final point in template.points) {
      buffer.write(
        "        DiscoveryTemplatePoint('${_escape(point.name)}', "
        'DiscoveryPointType.${point.type}',
      );
      if (point.quantity != 1) {
        buffer.write(', quantity: ${point.quantity}');
      }
      buffer.writeln('),');
    }
    buffer
      ..writeln('      ],')
      ..writeln('    ),');
  }

  buffer
    ..writeln('  ];')
    ..writeln('}');
  return buffer.toString();
}

String _categoryFor(String name) {
  final upper = name.toUpperCase();
  if (upper.contains('HAVA SANTRAL') ||
      upper.contains('HANDLING UNIT') ||
      upper.contains('GERİ KAZANIM SANTRAL') ||
      upper.contains('RECOVERY UNIT')) {
    return 'Hava Santralleri';
  }
  if (upper.contains('KAZAN')) return 'Isıtma Kazanları';
  if (upper.contains('HİDROFOR')) return 'Hidroforlar';
  if (upper.contains('POMPA') || upper.contains('PUMP')) return 'Pompalar';
  if (upper.contains('FAN')) return 'Fanlar';
  if (upper.contains('SENSÖR') || upper.contains('SENSOR')) return 'Sensörler';
  if (upper.contains('CHILLER')) return 'Soğutma Grupları';
  if (upper.contains('KULE') || upper.contains('TOWER')) {
    return 'Soğutma Kuleleri';
  }
  if (upper.contains('BOYLER')) return 'Boylerler';
  if (upper.contains('EŞANJÖR')) return 'Eşanjörler';
  if (upper.contains('DEPO') || upper.contains('TANK')) return 'Depolar';
  if (upper.contains('SU YUMUŞATMA')) return 'Su Sistemleri';
  if (upper.contains('KOLLEKTÖR')) return 'Kollektörler';
  return 'Diğer HVAC Ekipmanları';
}

String _slug(String value) {
  const replacements = <String, String>{
    'ç': 'c',
    'Ç': 'c',
    'ğ': 'g',
    'Ğ': 'g',
    'ı': 'i',
    'İ': 'i',
    'ö': 'o',
    'Ö': 'o',
    'ş': 's',
    'Ş': 's',
    'ü': 'u',
    'Ü': 'u',
  };
  final normalized = value
      .split('')
      .map((character) => replacements[character] ?? character)
      .join()
      .toLowerCase();
  return normalized
      .replaceAll(RegExp('[^a-z0-9]+'), '-')
      .replaceAll(RegExp(r'^-+|-+$'), '');
}

String _escape(String value) {
  return value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$');
}

class _Template {
  _Template(this.name);

  String name;
  final List<_Point> points = [];
}

class _Point {
  const _Point(this.name, this.type, this.quantity);

  final String name;
  final String type;
  final int quantity;
}
