-- ==============================================================================
-- MIGRATION: 20260817_personnel_card_and_serial_loans.sql
-- Personel Cari Benzeri Takip Kartı, Seri Numaralı Zimmetler ve Notlar
-- ==============================================================================

-- 1. product_stock_loans tablosunu genişletme
alter table public.product_stock_loans
add column if not exists serial_number text,
add column if not exists loan_batch_id text,
add column if not exists job_code text,
add column if not exists ticket_id uuid references public.tickets(id) on delete set null;

create index if not exists product_stock_loans_serial_idx
on public.product_stock_loans (serial_number);

create index if not exists product_stock_loans_batch_idx
on public.product_stock_loans (loan_batch_id);

create index if not exists product_stock_loans_job_idx
on public.product_stock_loans (job_code);

-- 2. stock_movements tablosunu genişletme
alter table public.stock_movements
add column if not exists serial_number text,
add column if not exists job_code text,
add column if not exists ticket_id uuid references public.tickets(id) on delete set null;

create index if not exists stock_movements_serial_idx
on public.stock_movements (serial_number);

-- 3. personnel_notes (Personel Not Defteri) Tablosu
create table if not exists public.personnel_notes (
    id bigint generated by default as identity primary key,
    personnel_id uuid not null references public.profiles(id) on delete cascade,
    note text not null,
    created_by uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists personnel_notes_personnel_id_idx
on public.personnel_notes (personnel_id, created_at desc);

alter table public.personnel_notes enable row level security;

drop policy if exists "personnel_notes_select_staff" on public.personnel_notes;
create policy "personnel_notes_select_staff"
on public.personnel_notes for select
to authenticated
using (
    exists (
        select 1 from public.profiles
        where id = auth.uid()
          and role in ('admin', 'manager', 'stock_manager', 'supervisor')
    )
);

drop policy if exists "personnel_notes_insert_staff" on public.personnel_notes;
create policy "personnel_notes_insert_staff"
on public.personnel_notes for insert
to authenticated
with check (
    exists (
        select 1 from public.profiles
        where id = auth.uid()
          and role in ('admin', 'manager', 'stock_manager', 'supervisor')
    )
);

drop policy if exists "personnel_notes_delete_staff" on public.personnel_notes;
create policy "personnel_notes_delete_staff"
on public.personnel_notes for delete
to authenticated
using (
    exists (
        select 1 from public.profiles
        where id = auth.uid()
          and role in ('admin', 'manager', 'stock_manager')
    )
);

-- 4. Çoklu Seri Numarasıyla Tekil Zimmet Çıkışı Yapan RPC Fonksiyonu
create or replace function public.register_serial_stock_loans(
    p_product_id text,
    p_personnel_id uuid,
    p_serial_numbers text[],
    p_job_code text default null,
    p_note text default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
    v_actor_role text;
    v_personnel_name text;
    v_before numeric(14,2);
    v_after numeric(14,2);
    v_total_qty integer;
    v_serial text;
    v_batch_id text;
    v_sn_trimmed text;
begin
    -- 1. Yetki kontrolü
    select role::text into v_actor_role
    from public.profiles where id = auth.uid();
    if v_actor_role not in ('admin', 'manager', 'stock_manager') then
        raise exception 'Bu islem icin stok yetkisi gerekir.';
    end if;

    v_total_qty := coalesce(array_length(p_serial_numbers, 1), 0);
    if v_total_qty <= 0 then
        raise exception 'En az bir seri numarasi girilmelidir.';
    end if;

    -- 2. Personel bilgisi
    select coalesce(nullif(trim(full_name), ''), email, id::text)
    into v_personnel_name
    from public.profiles where id = p_personnel_id;
    if not found then
        raise exception 'Personel bulunamadi.';
    end if;

    -- 3. Stok miktarı kontrolü ve düşümü
    select stock_quantity into v_before
    from public.products where id = p_product_id for update;
    if not found then
        raise exception 'Urun bulunamadi.';
    end if;

    v_after := v_before - v_total_qty;
    if v_after < 0 then
        raise exception 'Stok yetersiz! Depoda % adet var, % adet zimmetlenmek istendi.', v_before, v_total_qty;
    end if;

    update public.products
    set stock_quantity = v_after,
        updated_at = timezone('utc', now())
    where id = p_product_id;

    -- 4. Batch ID üret (Örn: BATCH-1700000000000)
    v_batch_id := 'BATCH-' || floor(extract(epoch from now()) * 1000)::text;

    -- 5. Her seri no için tekil product_stock_loans ve stock_movements satırı oluştur
    foreach v_serial in array p_serial_numbers
    loop
        v_sn_trimmed := nullif(trim(v_serial), '');
        if v_sn_trimmed is not null then
            insert into public.product_stock_loans (
                product_id,
                personnel_id,
                personnel_name,
                quantity,
                serial_number,
                loan_batch_id,
                job_code,
                note,
                status,
                borrowed_at,
                created_by
            ) values (
                p_product_id,
                p_personnel_id,
                v_personnel_name,
                1,
                v_sn_trimmed,
                v_batch_id,
                nullif(trim(coalesce(p_job_code, '')), ''),
                nullif(trim(coalesce(p_note, '')), ''),
                'borrowed',
                timezone('utc', now()),
                auth.uid()
            );

            insert into public.stock_movements (
                product_id,
                movement_type,
                quantity,
                quantity_before,
                quantity_after,
                reason,
                destination,
                note,
                serial_number,
                job_code,
                created_by
            ) values (
                p_product_id,
                'out',
                1,
                v_before,
                v_after,
                'Personele zimmetlendi (Seri No: ' || v_sn_trimmed || ')',
                v_personnel_name,
                nullif(trim(coalesce(p_note, '')), ''),
                v_sn_trimmed,
                nullif(trim(coalesce(p_job_code, '')), ''),
                auth.uid()
            );
        end if;
    end loop;

    return v_batch_id;
end;
$$;

-- 5. defective_products tablosunu genişletme
alter table public.defective_products
add column if not exists serial_number text;

create index if not exists defective_products_serial_idx
on public.defective_products (serial_number);

