-- Arızalı Ürün ve Garanti/RMA Takip Tablosu
create table if not exists public.defective_products (
    id bigint generated by default as identity primary key,
    product_id text not null references public.products(id) on delete cascade,
    reported_by_name text,
    quantity integer not null default 1 check (quantity > 0),
    fault_description text,
    job_code text,
    status text not null default 'in_faulty_stock'
        check (status in ('in_faulty_stock', 'shipped_to_supplier', 'repaired_returned', 'replaced', 'scrapped')),
    tracking_number text,
    supplier_name text,
    notes text,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    created_by uuid references public.profiles(id) on delete set null
);

create index if not exists defective_products_status_idx on public.defective_products (status, created_at desc);

alter table public.defective_products enable row level security;

drop policy if exists "defective_products_select_authenticated" on public.defective_products;
create policy "defective_products_select_authenticated"
on public.defective_products for select
to authenticated using (true);

drop policy if exists "defective_products_all_staff" on public.defective_products;
create policy "defective_products_all_staff"
on public.defective_products for all
to authenticated using (
    exists (
        select 1 from public.profiles
        where id = auth.uid()
          and role in ('admin', 'manager', 'stock_manager')
    )
);
