-- Kritik stok takibi ilk fiziksel giristen sonra baslar.
-- Personele verilen urunler tekliflerden bagimsiz acik borc olarak izlenir.

alter table public.products
add column if not exists stock_tracking_started boolean not null default false;

alter table public.stock_movements
add column if not exists product_id text references public.products(id) on delete cascade;

alter table public.stock_movements
alter column inventory_id drop not null;

update public.products
set stock_tracking_started = true
where stock_quantity > 0
  and stock_tracking_started = false;

create table if not exists public.product_stock_loans (
    id bigint generated by default as identity primary key,
    product_id text not null references public.products(id) on delete restrict,
    personnel_id uuid not null references public.profiles(id) on delete restrict,
    personnel_name text not null,
    quantity integer not null check (quantity > 0),
    note text,
    status text not null default 'borrowed'
        check (status in ('borrowed', 'returned', 'consumed')),
    borrowed_at timestamptz not null default timezone('utc', now()),
    closed_at timestamptz,
    created_by uuid references public.profiles(id) on delete set null,
    closed_by uuid references public.profiles(id) on delete set null
);

create index if not exists product_stock_loans_open_idx
on public.product_stock_loans (status, borrowed_at desc);

create index if not exists product_stock_loans_personnel_idx
on public.product_stock_loans (personnel_id, status);

alter table public.product_stock_loans enable row level security;

drop policy if exists "product_stock_loans_select_staff" on public.product_stock_loans;
create policy "product_stock_loans_select_staff"
on public.product_stock_loans for select
to authenticated
using (
    exists (
        select 1 from public.profiles
        where id = auth.uid()
          and role in ('admin', 'manager', 'stock_manager')
    )
);

create or replace function public.list_stock_personnel()
returns table (
    id uuid,
    email text,
    full_name text,
    role text
)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_actor_role text;
begin
    select p.role::text into v_actor_role
    from public.profiles p where p.id = auth.uid();
    if v_actor_role not in ('admin', 'manager', 'stock_manager') then
        raise exception 'Bu islem icin stok yetkisi gerekir.';
    end if;

    return query
    select p.id, p.email, p.full_name, p.role::text
    from public.profiles p
    where p.role::text not in ('pending', 'partner_user', 'partner')
    order by coalesce(nullif(trim(p.full_name), ''), p.email, p.id::text);
end;
$$;

create or replace function public.register_product_stock_movement(
    p_product_id text,
    p_movement_type text,
    p_quantity integer,
    p_reason text default null,
    p_destination text default null,
    p_note text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_before numeric(14,2);
    v_after numeric(14,2);
    v_actor_role text;
begin
    select role::text into v_actor_role
    from public.profiles where id = auth.uid();

    if v_actor_role not in ('admin', 'manager', 'stock_manager') then
        raise exception 'Bu islem icin stok yetkisi gerekir.';
    end if;
    if p_movement_type not in ('in', 'out') then
        raise exception 'Gecersiz stok hareketi.';
    end if;
    if p_quantity <= 0 then
        raise exception 'Adet 0dan buyuk olmali.';
    end if;

    select stock_quantity into v_before
    from public.products where id = p_product_id for update;
    if not found then raise exception 'Urun stok kaydi bulunamadi.'; end if;

    v_after := case when p_movement_type = 'in'
        then v_before + p_quantity else v_before - p_quantity end;
    if v_after < 0 then raise exception 'Stok yetersiz! Mevcut: %', v_before; end if;

    update public.products
    set stock_quantity = v_after,
        stock_tracking_started = stock_tracking_started or p_movement_type = 'in',
        updated_at = timezone('utc', now())
    where id = p_product_id;

    insert into public.stock_movements (
        product_id, movement_type, quantity, quantity_before, quantity_after,
        reason, destination, note, created_by
    ) values (
        p_product_id, p_movement_type, p_quantity, v_before, v_after,
        nullif(trim(coalesce(p_reason, '')), ''),
        nullif(trim(coalesce(p_destination, '')), ''),
        nullif(trim(coalesce(p_note, '')), ''), auth.uid()
    );
end;
$$;

create or replace function public.register_product_stock_loan(
    p_product_id text,
    p_personnel_id uuid,
    p_quantity integer,
    p_note text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_before numeric(14,2);
    v_after numeric(14,2);
    v_actor_role text;
    v_personnel_name text;
    v_loan_id bigint;
begin
    select role::text into v_actor_role
    from public.profiles where id = auth.uid();
    if v_actor_role not in ('admin', 'manager', 'stock_manager') then
        raise exception 'Bu islem icin stok yetkisi gerekir.';
    end if;
    if p_quantity <= 0 then raise exception 'Adet 0dan buyuk olmali.'; end if;

    select coalesce(nullif(trim(full_name), ''), email, id::text)
    into v_personnel_name
    from public.profiles where id = p_personnel_id;
    if not found then raise exception 'Personel bulunamadi.'; end if;

    select stock_quantity into v_before
    from public.products where id = p_product_id for update;
    if not found then raise exception 'Urun stok kaydi bulunamadi.'; end if;
    v_after := v_before - p_quantity;
    if v_after < 0 then raise exception 'Stok yetersiz! Mevcut: %', v_before; end if;

    update public.products
    set stock_quantity = v_after, updated_at = timezone('utc', now())
    where id = p_product_id;

    insert into public.product_stock_loans (
        product_id, personnel_id, personnel_name, quantity, note, created_by
    ) values (
        p_product_id, p_personnel_id, v_personnel_name, p_quantity,
        nullif(trim(coalesce(p_note, '')), ''), auth.uid()
    ) returning id into v_loan_id;

    insert into public.stock_movements (
        product_id, movement_type, quantity, quantity_before, quantity_after,
        reason, destination, note, created_by
    ) values (
        p_product_id, 'out', p_quantity, v_before, v_after,
        'Personele verildi', v_personnel_name,
        nullif(trim(coalesce(p_note, '')), ''), auth.uid()
    );

    return v_loan_id;
end;
$$;

create or replace function public.close_product_stock_loan(
    p_loan_id bigint,
    p_resolution text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_loan public.product_stock_loans%rowtype;
    v_before numeric(14,2);
    v_after numeric(14,2);
    v_actor_role text;
begin
    select role::text into v_actor_role
    from public.profiles where id = auth.uid();
    if v_actor_role not in ('admin', 'manager', 'stock_manager') then
        raise exception 'Bu islem icin stok yetkisi gerekir.';
    end if;
    if p_resolution not in ('returned', 'consumed') then
        raise exception 'Gecersiz kapatma turu.';
    end if;

    select * into v_loan
    from public.product_stock_loans where id = p_loan_id for update;
    if not found then raise exception 'Personel borcu bulunamadi.'; end if;
    if v_loan.status <> 'borrowed' then raise exception 'Bu borc zaten kapatilmis.'; end if;

    if p_resolution = 'returned' then
        select stock_quantity into v_before
        from public.products where id = v_loan.product_id for update;
        v_after := v_before + v_loan.quantity;
        update public.products
        set stock_quantity = v_after, updated_at = timezone('utc', now())
        where id = v_loan.product_id;

        insert into public.stock_movements (
            product_id, movement_type, quantity, quantity_before, quantity_after,
            reason, destination, note, created_by
        ) values (
            v_loan.product_id, 'in', v_loan.quantity, v_before, v_after,
            'Personelden iade', v_loan.personnel_name, v_loan.note, auth.uid()
        );
    end if;

    update public.product_stock_loans
    set status = p_resolution,
        closed_at = timezone('utc', now()),
        closed_by = auth.uid()
    where id = p_loan_id;
end;
$$;

revoke all on function public.register_product_stock_movement(
    text, text, integer, text, text, text
) from public;
revoke all on function public.list_stock_personnel() from public;
revoke all on function public.register_product_stock_loan(
    text, uuid, integer, text
) from public;
revoke all on function public.close_product_stock_loan(
    bigint, text
) from public;

grant execute on function public.register_product_stock_movement(
    text, text, integer, text, text, text
) to authenticated;
grant execute on function public.register_product_stock_loan(
    text, uuid, integer, text
) to authenticated;
grant execute on function public.close_product_stock_loan(
    bigint, text
) to authenticated;
grant execute on function public.list_stock_personnel() to authenticated;
