create table if not exists public.fault_records (
  id uuid primary key default gen_random_uuid(),
  fault_code text not null default '-',
  title text not null,
  body text not null,
  status text not null default 'open',
  device_brand text,
  device_model text,
  linked_ticket_id uuid references public.tickets (id) on delete set null,
  assignee_id uuid references public.profiles (id) on delete set null,
  assignee_name text,
  created_by uuid references auth.users (id) on delete set null,
  created_by_name text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint fault_records_status_check
    check (status in ('open', 'monitoring', 'resolved', 'closed'))
);

create index if not exists fault_records_linked_ticket_idx
  on public.fault_records (linked_ticket_id);

create index if not exists fault_records_created_at_idx
  on public.fault_records (created_at desc);

create table if not exists public.fault_record_notes (
  id bigint generated by default as identity primary key,
  fault_record_id uuid not null references public.fault_records (id) on delete cascade,
  note text not null,
  note_type text not null default 'note',
  user_id uuid references auth.users (id) on delete set null,
  user_name text,
  user_role text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists fault_record_notes_fault_record_idx
  on public.fault_record_notes (fault_record_id, created_at asc);

alter table public.fault_records enable row level security;
alter table public.fault_record_notes enable row level security;

create policy "Authenticated users can read fault records"
  on public.fault_records
  for select
  to authenticated
  using (true);

create policy "Authenticated users can insert fault records"
  on public.fault_records
  for insert
  to authenticated
  with check (true);

create policy "Authenticated users can update fault records"
  on public.fault_records
  for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated users can read fault record notes"
  on public.fault_record_notes
  for select
  to authenticated
  using (true);

create policy "Authenticated users can insert fault record notes"
  on public.fault_record_notes
  for insert
  to authenticated
  with check (true);

